# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import time

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv('cities_data.csv')
cities_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Codrington,-38.2667,141.9667,43.41,95,5,7.72,AU,1653241331
1,Yulara,-25.2406,130.9889,56.19,42,64,7.85,AU,1653241368
2,Mataura,-46.1927,168.8643,43.79,92,99,7.20,NZ,1653241368
3,Burayevo,55.8407,55.4083,35.17,90,82,4.25,RU,1653241369
4,Ahipara,-35.1667,173.1667,59.07,77,100,10.58,NZ,1653241369
...,...,...,...,...,...,...,...,...,...
569,Staryy Nadym,65.6118,72.6842,46.92,75,99,23.60,RU,1653241597
570,Kumul,42.8000,93.4500,79.84,17,94,8.75,CN,1653241597
571,Lavrentiya,65.5833,-171.0000,38.23,74,100,7.65,RU,1653241597
572,Urubichá,-15.3833,-62.9500,83.75,46,89,3.89,BO,1653241598
573,Bridgetown,13.1000,-59.6167,86.49,66,20,20.71,BB,1653241598

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Configure gmaps with API key
#gmaps.configure(api_key=g_key)

# Store 'Lat' and 'Lng' into  locations
locations = cities_df[['Lat', 'Lng']]

#Humidity as the weight
humidity = cities_df["Humidity"].astype(float)

#Heatmap layer to map
fig = gmaps.figure(zoom_level=10, center= (4,-72))
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                 dissipating=False, max_intensity=100,
                                 point_radius = 2)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
ideal_weather = cities_df.loc[(cities_df['Max Temp'] >=80)&(cities_df['Wind Speed']<10)\
                              &(cities_df['Cloudiness']>=50), :].dropna(how='any')
ideal_weather

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
98,Champerico,14.3000,-91.9167,88.34,67,83,8.79,GT,1653241329
108,Duku,11.2361,4.9073,81.73,62,93,9.51,NG,1653241412
146,Nova Russas,-4.7067,-40.5631,83.32,56,75,6.46,BR,1653241425
226,Tarauacá,-8.1614,-70.7656,86.86,53,73,1.34,BR,1653241370
269,Sapa,5.1544,120.3241,81.18,79,100,7.56,PH,1653241476
281,Acapulco de Juárez,16.8634,-99.8901,84.02,58,75,5.75,MX,1653241356
289,Cobija,-11.0267,-68.7692,87.98,62,75,0.00,BO,1653241482
296,Mombaça,-5.7431,-39.6275,83.08,54,88,7.76,BR,1653241485
317,Marzuq,14.4000,46.4667,81.07,13,100,0.65,YE,1653241494
333,Salalah,17.0151,54.0924,84.29,84,75,8.05,OM,1653241500
334,Maturin,9.7500,-63.1767,92.82,37,77,9.06,VE,1653241281
344,Kutum,14.2000,24.6667,83.01,15,87,8.30,SD,1653241505
359,Mayahi,13.9553,7.6712,93.76,11,80,4.97,NE,1653241512
363,Pontes e Lacerda,-15.2261,-59.3353,87.93,35,76,3.31,BR,1653241514
369,Basco,20.4487,121.9702,81.25,80,50,9.71,PH,1653241517
376,Birao,10.2849,22.7882,92.23,20,100,5.53,CF,1653241483
384,Leer,8.3018,30.1418,82.02,65,90,3.60,SS,1653241522
390,Tiznit Province,29.5833,-9.5000,80.04,37,87,5.28,MA,1653241525
402,Tangkak,2.2673,102.5453,80.47,94,97,0.83,MY,1653241530
404,Auka,14.9333,-83.8333,82.29,91,100,1.43,HN,1653241530
420,Douentza,14.9951,-2.9517,90.25,34,100,4.00,ML,1653241537
440,Palmer,42.1584,-72.3287,88.90,55,75,9.22,US,1653241419
447,Yaan,7.3833,8.5667,80.83,71,93,6.49,NG,1653241546
481,Pundaguitan,6.3711,126.1689,81.25,77,75,2.21,PH,1653241559
486,Mawlaik,23.6333,94.4167,80.17,70,69,1.36,MM,1653241561
502,Boca do Acre,-8.7522,-67.3978,89.94,44,65,2.17,BR,1653241568
516,Tanout,14.9709,8.8879,95.76,12,95,6.31,NE,1653241575
572,Urubichá,-15.3833,-62.9500,83.75,46,89,3.89,BO,1653241598

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
#Store into variable named hotel_df & add a "Hotel Name" column to the DataFrame.
hotel_df = ideal_weather
hotel_df ["Hotel Name"] = ""
hotel_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
98,Champerico,14.3000,-91.9167,88.34,67,83,8.79,GT,1653241329,
108,Duku,11.2361,4.9073,81.73,62,93,9.51,NG,1653241412,
146,Nova Russas,-4.7067,-40.5631,83.32,56,75,6.46,BR,1653241425,
226,Tarauacá,-8.1614,-70.7656,86.86,53,73,1.34,BR,1653241370,
269,Sapa,5.1544,120.3241,81.18,79,100,7.56,PH,1653241476,

In [7]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : g_key}

for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    
    params["location"] = f"{lat},{lng}"
    
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    results = response['results']
    
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']

    # if there is no hotel available, show missing field
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")
    
    # Wait 1 sec to make another api request to avoid SSL Error
    time.sleep(1)

# Print end of search once searching is completed
print("-------End of Search-------")

Retrieving Results for Index 98: Champerico.
Closest hotel in Champerico is Hotel Miramar.
------------
Retrieving Results for Index 108: Duku.
Missing field/result... skipping.
------------
Retrieving Results for Index 146: Nova Russas.
Closest hotel in Nova Russas is Magnum Hotel.
------------
Retrieving Results for Index 226: Tarauacá.
Closest hotel in Tarauacá is Hotel Ferreira.
------------
Retrieving Results for Index 269: Sapa.
Missing field/result... skipping.
------------
Retrieving Results for Index 281: Acapulco de Juárez.
Closest hotel in Acapulco de Juárez is Hotel Amarea Acapulco.
------------
Retrieving Results for Index 289: Cobija.
Closest hotel in Cobija is Hotel Dorado.
------------
Retrieving Results for Index 296: Mombaça.
Closest hotel in Mombaça is Mombaça Premium Hotel.
------------
Retrieving Results for Index 317: Marzuq.
Missing field/result... skipping.
------------
Retrieving Results for Index 333: Salalah.
Closest hotel in Salalah is Salalah Gardens Hotel.
------------
Retrieving Results for Index 334: Maturin.
Closest hotel in Maturin is Hotel Stauffer International.
------------
Retrieving Results for Index 344: Kutum.
Missing field/result... skipping.
------------
Retrieving Results for Index 359: Mayahi.
Missing field/result... skipping.
------------
Retrieving Results for Index 363: Pontes e Lacerda.
Closest hotel in Pontes e Lacerda is Plaza Hotel.
------------
Retrieving Results for Index 369: Basco.
Closest hotel in Basco is Fundacion Pacita.
------------
Retrieving Results for Index 376: Birao.
Missing field/result... skipping.
------------
Retrieving Results for Index 384: Leer.
Closest hotel in Leer is Leer Humanitarian Hub.
------------
Retrieving Results for Index 390: Tiznit Province.
Missing field/result... skipping.
------------
Retrieving Results for Index 402: Tangkak.
Closest hotel in Tangkak is Ophir Hotel.
------------
Retrieving Results for Index 404: Auka.
Missing field/result... skipping.
------------
Retrieving Results for Index 420: Douentza.
Missing field/result... skipping.
------------
Retrieving Results for Index 440: Palmer.
Closest hotel in Palmer is The Trainmaster's Inn.
------------
Retrieving Results for Index 447: Yaan.
Missing field/result... skipping.
------------
Retrieving Results for Index 481: Pundaguitan.
Closest hotel in Pundaguitan is El Don Resort.
------------
Retrieving Results for Index 486: Mawlaik.
Closest hotel in Mawlaik is Shenadi Guesthouse.
------------
Retrieving Results for Index 502: Boca do Acre.
Closest hotel in Boca do Acre is Hotel Alice.
------------
Retrieving Results for Index 516: Tanout.
Missing field/result... skipping.
------------
Retrieving Results for Index 572: Urubichá.
Missing field/result... skipping.
------------
-------End of Search-------

In [8]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
98,Champerico,14.3000,-91.9167,88.34,67,83,8.79,GT,1653241329,Hotel Miramar
108,Duku,11.2361,4.9073,81.73,62,93,9.51,NG,1653241412,
146,Nova Russas,-4.7067,-40.5631,83.32,56,75,6.46,BR,1653241425,Magnum Hotel
226,Tarauacá,-8.1614,-70.7656,86.86,53,73,1.34,BR,1653241370,Hotel Ferreira
269,Sapa,5.1544,120.3241,81.18,79,100,7.56,PH,1653241476,
281,Acapulco de Juárez,16.8634,-99.8901,84.02,58,75,5.75,MX,1653241356,Hotel Amarea Acapulco
289,Cobija,-11.0267,-68.7692,87.98,62,75,0.00,BO,1653241482,Hotel Dorado
296,Mombaça,-5.7431,-39.6275,83.08,54,88,7.76,BR,1653241485,Mombaça Premium Hotel
317,Marzuq,14.4000,46.4667,81.07,13,100,0.65,YE,1653241494,
333,Salalah,17.0151,54.0924,84.29,84,75,8.05,OM,1653241500,Salalah Gardens Hotel
334,Maturin,9.7500,-63.1767,92.82,37,77,9.06,VE,1653241281,Hotel Stauffer International
344,Kutum,14.2000,24.6667,83.01,15,87,8.30,SD,1653241505,
359,Mayahi,13.9553,7.6712,93.76,11,80,4.97,NE,1653241512,
363,Pontes e Lacerda,-15.2261,-59.3353,87.93,35,76,3.31,BR,1653241514,Plaza Hotel
369,Basco,20.4487,121.9702,81.25,80,50,9.71,PH,1653241517,Fundacion Pacita
376,Birao,10.2849,22.7882,92.23,20,100,5.53,CF,1653241483,
384,Leer,8.3018,30.1418,82.02,65,90,3.60,SS,1653241522,Leer Humanitarian Hub
390,Tiznit Province,29.5833,-9.5000,80.04,37,87,5.28,MA,1653241525,
402,Tangkak,2.2673,102.5453,80.47,94,97,0.83,MY,1653241530,Ophir Hotel
404,Auka,14.9333,-83.8333,82.29,91,100,1.43,HN,1653241530,
420,Douentza,14.9951,-2.9517,90.25,34,100,4.00,ML,1653241537,
440,Palmer,42.1584,-72.3287,88.90,55,75,9.22,US,1653241419,The Trainmaster's Inn
447,Yaan,7.3833,8.5667,80.83,71,93,6.49,NG,1653241546,
481,Pundaguitan,6.3711,126.1689,81.25,77,75,2.21,PH,1653241559,El Don Resort
486,Mawlaik,23.6333,94.4167,80.17,70,69,1.36,MM,1653241561,Shenadi Guesthouse
502,Boca do Acre,-8.7522,-67.3978,89.94,44,65,2.17,BR,1653241568,Hotel Alice
516,Tanout,14.9709,8.8879,95.76,12,95,6.31,NE,1653241575,
572,Urubichá,-15.3833,-62.9500,83.75,46,89,3.89,BO,1653241598,

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [10]:
# Add marker layer ontop of heat map
figure_layout = {
    'width': '900px',
    'height': '600px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'}

fig = gmaps.figure(layout=figure_layout,zoom_level=2,center=(15,25))
    
hotel_layer = gmaps.marker_layer(
    locations,info_box_content=[info_box_template.format(**row) for index, row in hotel_df.iterrows()]
)

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)
# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', margin='0 auto 0 auto', padding='1px', wi…